jdbc.url=jdbc:mysql://localhost:3306/kgraph?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&createDatabaseIfNotExist=true
jdbc.username=root
jdbc.password=liutaotao0202

mybatis.typeAliasesPackage=com.study.kgraph.entity
mybatis.mapperLocations=classpath:mapper/*.xml

upload.root=/Users/liuzhenyu_macbookpro/Desktop/AI-Study/uploads

aliyun.app-key=NAAPOsgEKFA7YzbW
aliyun.access-key-id=LTAI5tFRvVuhA8TfmuVChtWG
aliyun.access-key-secret=S5nlLh74qPGqqgwaFpOwuBH0Zexmsz
aliyun.region=cn-shanghai
aliyun.oss.endpoint=https://oss-cn-shanghai.aliyuncs.com
aliyun.oss.bucket=kgraph-audio-study

modelscope.api.key=ms-2d143f6e-cad4-45fe-a19f-3ba1d458028c
modelscope.api.url=https://api-inference.modelscope.cn/v1/chat/completions
modelscope.model=Qwen/Qwen3-VL-8B-Instruct
